/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as HelpRouteImport } from './routes/help'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProceduresRouteImport } from './routes/procedures'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceServiceIdRouteImport } from './routes/service.$serviceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProceduresRoute = ProceduresRouteImport.update({
  id: '/procedures',
  path: '/procedures',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceServiceIdRoute = ServiceServiceIdRouteImport.update({
  id: '/service/$serviceId',
  path: '/service/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/procedures': typeof ProceduresRoute
  '/services': typeof ServicesRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/procedures': typeof ProceduresRoute
  '/services': typeof ServicesRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/onboarding': typeof OnboardingRoute
  '/procedures': typeof ProceduresRoute
  '/services': typeof ServicesRoute
  '/service/$serviceId': typeof ServiceServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/help'
    | '/onboarding'
    | '/procedures'
    | '/services'
    | '/service/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/help'
    | '/onboarding'
    | '/procedures'
    | '/services'
    | '/service/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/help'
    | '/onboarding'
    | '/procedures'
    | '/services'
    | '/service/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRoute
  HelpRoute: typeof HelpRoute
  OnboardingRoute: typeof OnboardingRoute
  ProceduresRoute: typeof ProceduresRoute
  ServicesRoute: typeof ServicesRoute
  ServiceServiceIdRoute: typeof ServiceServiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procedures': {
      id: '/procedures'
      path: '/procedures'
      fullPath: '/procedures'
      preLoaderRoute: typeof ProceduresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/$serviceId': {
      id: '/service/$serviceId'
      path: '/service/$serviceId'
      fullPath: '/service/$serviceId'
      preLoaderRoute: typeof ServiceServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRoute,
  HelpRoute: HelpRoute,
  OnboardingRoute: OnboardingRoute,
  ProceduresRoute: ProceduresRoute,
  ServicesRoute: ServicesRoute,
  ServiceServiceIdRoute: ServiceServiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
