import type { DocumentDetail, Place, Service } from "./types";
import passportImg from "@/assets/svc-passport.jpg";
import idImg from "@/assets/svc-id.jpg";
import birthImg from "@/assets/svc-birth.jpg";
import licenseImg from "@/assets/svc-license.jpg";
import universityImg from "@/assets/svc-university.jpg";
import jobImg from "@/assets/svc-job.jpg";
import bankImg from "@/assets/svc-bank.jpg";

export const EGYPT_DIGITAL_URL = "https://digital.gov.eg/";

export const GOVERNORATES = [
  "القاهرة",
  "الجيزة",
  "الإسكندرية",
  "القليوبية",
  "الشرقية",
  "الدقهلية",
  "الغربية",
  "المنوفية",
  "البحيرة",
  "كفر الشيخ",
  "دمياط",
  "بورسعيد",
  "الإسماعيلية",
  "السويس",
  "شمال سيناء",
  "جنوب سيناء",
  "بني سويف",
  "الفيوم",
  "المنيا",
  "أسيوط",
  "سوهاج",
  "قنا",
  "الأقصر",
  "أسوان",
  "البحر الأحمر",
  "مطروح",
  "الوادي الجديد",
];

/** Shared document library. All figures are indicative estimates, not official prices. */
export const DOCUMENTS: Record<string, DocumentDetail> = {
  nid: {
    id: "nid",
    name: "بطاقة الرقم القومي",
    why: "هي إثبات شخصيتك الأساسي، ومطلوبة في كل إجراء تقريبًا.",
    where: "أقرب سجل مدني تابع لمحل سكنك.",
    requirements: [
      "شهادة الميلاد المميكنة",
      "٢ صورة شخصية حديثة خلفية بيضاء",
      "إثبات محل السكن (فاتورة مرافق أو عقد)",
      "لو طالب أو موظف: إثبات المهنة",
    ],
    online: true,
    onlineNote: "التجديد بالتوصيل للمنزل متاح عبر منصة مصر الرقمية في أماكن كثيرة.",
    needsVisit: true,
    cost: "تقديري: 100–225 EGP (قد تختلف حسب المكان ونوع الخدمة)",
    time: "تقديري: من يوم لـ 15 يوم",
    openingHours: "الأحد–الخميس، 8 ص – 2 م (بعض المكاتب بتفتح لوقت متأخر)",
    requiredId: "أي إثبات شخصية متاح، أو شهادة الميلاد لأول مرة",
    notes: "راجع كل بياناتك (الاسم، تاريخ الميلاد، العنوان) قبل ما تستلم البطاقة.",
    accessibilityInfo: "معظم السجلات المدنية الجديدة فيها مدخل منحدر وشباك أولوية لكبار السن.",
    howTo: [
      "روح أقرب سجل مدني.",
      "خد معاك شهادة الميلاد المميكنة و٢ صورة.",
      "املأ استمارة البيانات (فيه موظف بيساعدك).",
      "ادفع الرسوم واستلم إيصال بميعاد الاستلام.",
    ],
  },
  birth: {
    id: "birth",
    name: "شهادة الميلاد المميكنة",
    why: "بتثبت تاريخ ومكان ميلادك، ومطلوبة في الجواز والبطاقة والجامعة.",
    where: "أي مكتب صحة أو سجل مدني، ومتاحة كذلك للطلب أونلاين مع التوصيل.",
    requirements: ["بطاقة الرقم القومي للطالب أو لولي الأمر", "بيانات الميلاد (الاسم الرباعي وتاريخ الميلاد)"],
    online: true,
    onlineNote: "الطلب أونلاين متاح عبر منصة مصر الرقمية مع توصيل للمنزل.",
    needsVisit: false,
    cost: "تقديري: 30–75 EGP (التوصيل للمنزل بيزيد التكلفة)",
    time: "تقديري: نفس اليوم في المكتب، أو 3–7 أيام للتوصيل",
    openingHours: "الأحد–الخميس، 8:30 ص – 2 م",
    requiredId: "بطاقة الرقم القومي",
    notes: "لو الشهادة قديمة (غير مميكنة) أغلب الجهات مش بتقبلها، اطلب النسخة المميكنة.",
    accessibilityInfo: "الطلب أونلاين هو الأسهل لو التحرك صعب عليك.",
    howTo: [
      "لو مش معاك شهادة الميلاد: روح أقرب مكتب صحة أو سجل مدني.",
      "خليك معاك بطاقة الرقم القومي.",
      "اطلب شهادة ميلاد مميكنة.",
      "راجع البيانات قبل ما تستلمها.",
    ],
  },
  photos: {
    id: "photos",
    name: "صور شخصية حديثة",
    why: "مطلوبة على كل الطلبات الرسمية، وبمقاس ومواصفات محددة.",
    where: "أي استوديو تصوير أو مركز خدمات طباعة.",
    requirements: ["الوش واضح وخلفية بيضاء", "مقاس 4×6 لمعظم الطلبات", "من غير نضارة شمس أو غطاء للوش"],
    online: false,
    needsVisit: true,
    cost: "تقديري: 25–60 EGP لـ 6 صور",
    time: "تقديري: من 10 دقايق لنص ساعة",
    openingHours: "معظم الاستوديوهات: 10 ص – 10 م",
    requiredId: "مش مطلوب إثبات",
    notes: "قول للاستوديو الورقة اللي هتقدم عليها، عشان يظبط المقاس المطلوب.",
    accessibilityInfo: "أغلب الاستوديوهات في الدور الأرضي؛ اسأل بالتليفون قبل ما تروح.",
  },
  form: {
    id: "form",
    name: "نموذج الطلب",
    why: "بيانات طلبك الرسمية. تقدر تجهزه في البيت وتوفر وقت في الطابور.",
    where: "متاح في المكتب، وتقدر تطبع نسخة تدريبية من هنا وتجهز بياناتك.",
    requirements: ["اسمك الرباعي كما في البطاقة", "الرقم القومي", "العنوان الحالي"],
    online: true,
    needsVisit: false,
    printable: true,
    cost: "تقديري: مجاني – 5 EGP للطباعة",
    time: "تقديري: 5–10 دقايق",
    notes: "النموذج المطبوع من هنا نموذج تجريبي للتحضير فقط، والنسخة الرسمية بتتسلم في المكتب.",
    stamp: {
      where: "شباك التصديق في نفس المكتب اللي بتقدم فيه",
      institution: "الجهة المسؤولة عن الخدمة (مصلحة الجوازات / السجل المدني)",
      bring: ["بطاقة الرقم القومي", "الإيصال بعد دفع الرسوم"],
      hours: "الأحد–الخميس، 8 ص – 1:30 م",
      appointment: "غالبًا من غير ميعاد، بس الحضور بدري بيقصر الانتظار.",
    },
  },
  oldPassport: {
    id: "oldPassport",
    name: "جواز السفر القديم",
    why: "مطلوب في التجديد أو البدل، لأنه بيثبت إصدارك السابق.",
    where: "معاك أنت، أو صورة منه لو ضايع.",
    requirements: ["الجواز الأصلي أو صورة من أول صفحة"],
    online: false,
    needsVisit: false,
    cost: "تقديري: لا يوجد",
    time: "—",
    notes: "لو الجواز ضايع، هتحتاج محضر فقد من قسم الشرطة.",
  },
  policeReport: {
    id: "policeReport",
    name: "محضر فقد",
    why: "مطلوب لإثبات فقدان الجواز أو البطاقة قبل استخراج بدل فاقد.",
    where: "أقرب قسم أو مركز شرطة.",
    requirements: ["إثبات شخصية", "أي صورة أو بيانات عن الورقة الضايعة"],
    online: false,
    needsVisit: true,
    cost: "تقديري: مجاني – 30 EGP",
    time: "تقديري: 30–90 دقيقة",
    openingHours: "24 ساعة",
    requiredId: "بطاقة الرقم القومي أو أي إثبات متاح",
    notes: "خد صورة من المحضر واحفظها معاك.",
  },
  militaryCert: {
    id: "militaryCert",
    name: "شهادة الموقف من التجنيد",
    why: "مطلوبة للشباب الذكور في سن التجنيد عند استخراج الجواز.",
    where: "منطقة التجنيد التابع لها محل ميلادك.",
    requirements: ["بطاقة الرقم القومي", "صورة شخصية", "شهادة الميلاد"],
    online: true,
    onlineNote: "بعض الخدمات متاحة إلكترونيًا حسب حالتك.",
    needsVisit: true,
    cost: "تقديري: 20–100 EGP",
    time: "تقديري: نفس اليوم – 3 أيام",
    openingHours: "السبت–الخميس، 8 ص – 1 م",
    notes: "المستندات بتختلف حسب حالتك (طالب / أدى الخدمة / معافى).",
  },
  medical: {
    id: "medical",
    name: "الكشف الطبي (نظر ودم)",
    why: "شرط أساسي لرخصة القيادة.",
    where: "الوحدة الصحية أو مركز الكشف المعتمد جوه وحدة المرور.",
    requirements: ["بطاقة الرقم القومي", "صورة شخصية"],
    online: false,
    needsVisit: true,
    cost: "تقديري: 50–150 EGP",
    time: "تقديري: 30–60 دقيقة",
    openingHours: "الأحد–الخميس، 8:30 ص – 1:30 م",
    accessibilityInfo: "اسأل عن شباك ذوي الاحتياجات في وحدة المرور.",
  },
  drivingTest: {
    id: "drivingTest",
    name: "اختبار القيادة والإشارات",
    why: "خطوة إجبارية لرخصة القيادة لأول مرة.",
    where: "وحدة المرور التابع لها محل سكنك.",
    requirements: ["إيصال دفع الرسوم", "الكشف الطبي", "بطاقة الرقم القومي"],
    online: false,
    needsVisit: true,
    cost: "تقديري: 100–300 EGP",
    time: "تقديري: نصف يوم",
    openingHours: "الأحد–الخميس، 8 ص – 12 م",
    notes: "الاختبار فيه جزء نظري (إشارات) وجزء عملي.",
  },
  criminalRecord: {
    id: "criminalRecord",
    name: "صحيفة الحالة الجنائية (الفيش)",
    why: "بتطلبها جهات كتير للتوظيف وبعض الإجراءات.",
    where: "مكتب الفيش والتشبيه في مديرية الأمن.",
    requirements: ["بطاقة الرقم القومي", "2 صورة شخصية"],
    online: true,
    onlineNote: "الطلب متاح إلكترونيًا في بعض المحافظات.",
    needsVisit: true,
    cost: "تقديري: 50–120 EGP",
    time: "تقديري: 2–7 أيام",
    openingHours: "الأحد–الخميس، 8 ص – 2 م",
  },
  residenceProof: {
    id: "residenceProof",
    name: "إثبات محل السكن",
    why: "بيثبت عنوانك الحالي عند تغيير البيانات.",
    where: "فاتورة كهرباء/غاز/مياه باسمك أو عقد إيجار موثق.",
    requirements: ["فاتورة حديثة (آخر 3 شهور) أو عقد"],
    online: false,
    needsVisit: false,
    cost: "تقديري: لا يوجد",
    time: "—",
    notes: "لو الفاتورة مش باسمك، خد إقرار من صاحب المسكن.",
  },
};

const PLACE_TEMPLATES: Omit<Place, "id" | "address" | "mapQuery">[] = [
  {
    name: "السجل المدني الرئيسي",
    type: "جهة حكومية",
    hours: "الأحد–الخميس 8 ص – 2 م",
    distanceKm: 1.8,
    travelMinutes: 12,
    accessibility: "مدخل منحدر + شباك أولوية",
  },
  {
    name: "مكتب الصحة",
    type: "جهة حكومية",
    hours: "الأحد–الخميس 8:30 ص – 2 م",
    distanceKm: 2.6,
    travelMinutes: 16,
    accessibility: "الدور الأرضي",
  },
  {
    name: "استوديو تصوير النور",
    type: "استوديو تصوير",
    hours: "يوميًا 10 ص – 10 م",
    distanceKm: 0.7,
    travelMinutes: 8,
    accessibility: "الدور الأرضي",
  },
  {
    name: "مركز خدمات وطباعة",
    type: "طباعة وخدمات",
    hours: "يوميًا 9 ص – 9 م",
    distanceKm: 1.1,
    travelMinutes: 9,
  },
  {
    name: "وحدة المرور",
    type: "جهة حكومية",
    hours: "الأحد–الخميس 8 ص – 1 م",
    distanceKm: 4.5,
    travelMinutes: 22,
    accessibility: "اسأل عن شباك ذوي الاحتياجات",
  },
  {
    name: "فرع البنك الأهلي",
    type: "بنك",
    hours: "الأحد–الخميس 8:30 ص – 3 م",
    distanceKm: 1.4,
    travelMinutes: 10,
    accessibility: "مدخل منحدر",
  },
];

export function placesFor(city: string): Place[] {
  const c = city || "مدينتك";
  return PLACE_TEMPLATES.map((p, i) => ({
    ...p,
    id: `place-${i}`,
    address: `${c} – عنوان تجريبي ${i + 1}`,
    mapQuery: `${p.name} ${c}`,
  }));
}

const yesNo = [
  { value: "yes", label: "أيوه" },
  { value: "no", label: "لا" },
];

export const SERVICES: Service[] = [
  {
    id: "passport",
    serviceName: "استخراج جواز سفر",
    shortName: "جواز السفر",
    description: "خطوات جواز السفر لأول مرة أو تجديد أو بدل فاقد.",
    image: passportImg,
    officialLink: EGYPT_DIGITAL_URL,
    lastUpdated: "2026-08-01",
    accessibilityInfo: "مكاتب الجوازات الكبيرة فيها شباك أولوية لكبار السن وذوي الاحتياجات.",
    questions: [
      {
        id: "type",
        text: "إيه نوع الطلب؟",
        options: [
          { value: "first", label: "أول مرة" },
          { value: "renew", label: "تجديد" },
          { value: "lost", label: "بدل فاقد" },
          { value: "damaged", label: "بدل تالف" },
          { value: "expired", label: "انتهت صلاحيته" },
        ],
      },
      {
        id: "hasOld",
        text: "هل معاك جواز السفر القديم؟",
        options: yesNo,
        showIf: (a) => ["renew", "damaged", "expired"].includes(a["type"] ?? ""),
      },
      {
        id: "dataChanged",
        text: "هل بياناتك الشخصية اتغيرت (الاسم أو العنوان)؟",
        options: yesNo,
        showIf: (a) => a["type"] !== "first",
      },
      {
        id: "male",
        text: "هل أنت شاب ذكر في سن التجنيد (18–30)؟",
        options: yesNo,
      },
    ],
    requiredDocuments: [
      { docId: "nid" },
      { docId: "birth", showIf: (a) => a["type"] === "first" },
      { docId: "photos" },
      { docId: "form" },
      { docId: "oldPassport", showIf: (a) => a["hasOld"] === "yes" },
      { docId: "policeReport", showIf: (a) => a["type"] === "lost" },
      { docId: "militaryCert", showIf: (a) => a["male"] === "yes" },
      { docId: "residenceProof", showIf: (a) => a["dataChanged"] === "yes" },
    ],
    steps: [
      { id: "prep", title: "جهّز مستنداتك", detail: "راجع الchecklist وجمّع كل ورقة ناقصة." },
      {
        id: "submit",
        title: "قدّم الطلب",
        detail: "روح مكتب الجوازات أو ابدأ الطلب من منصة مصر الرقمية، وادفع الرسوم.",
        cost: "تقديري: 500–1200 EGP حسب نوع الجواز والاستعجال",
        time: "تقديري: من ساعة لنص يوم في المكتب",
      },
      {
        id: "receive",
        title: "استلم جواز السفر",
        detail: "استلم بالإيصال في الميعاد المكتوب، وراجع بياناتك قبل ما تمشي.",
        time: "تقديري: 5–15 يوم عمل",
      },
    ],
    documents: DOCUMENTS,
    places: [],
  },
  {
    id: "national-id",
    serviceName: "بطاقة الرقم القومي",
    shortName: "الرقم القومي",
    description: "أول بطاقة، تجديد، تغيير بيانات أو بدل فاقد.",
    image: idImg,
    officialLink: EGYPT_DIGITAL_URL,
    lastUpdated: "2026-08-01",
    accessibilityInfo: "التجديد بالتوصيل للمنزل بيوفر عليك الحركة لو صعبة.",
    questions: [
      {
        id: "type",
        text: "إيه نوع الطلب؟",
        options: [
          { value: "first", label: "أول بطاقة (16 سنة)" },
          { value: "renew", label: "تجديد" },
          { value: "lost", label: "بدل فاقد" },
          { value: "update", label: "تغيير بيانات" },
        ],
      },
      { id: "hasBirth", text: "هل معاك شهادة ميلاد مميكنة؟", options: yesNo },
      {
        id: "moved",
        text: "هل غيّرت محل سكنك؟",
        options: yesNo,
        showIf: (a) => a["type"] !== "first",
      },
    ],
    requiredDocuments: [
      { docId: "birth" },
      { docId: "photos" },
      { docId: "form" },
      { docId: "policeReport", showIf: (a) => a["type"] === "lost" },
      { docId: "residenceProof", showIf: (a) => a["moved"] === "yes" || a["type"] === "first" },
    ],
    steps: [
      { id: "prep", title: "جهّز مستنداتك", detail: "خصوصًا شهادة الميلاد المميكنة والصور." },
      {
        id: "submit",
        title: "قدّم في السجل المدني",
        detail: "املأ الاستمارة، ادفع الرسوم، وخد الإيصال.",
        cost: "تقديري: 100–225 EGP",
        time: "تقديري: 1–3 ساعات",
      },
      {
        id: "receive",
        title: "استلم البطاقة",
        detail: "استلم من نفس المكتب أو بالتوصيل، وراجع كل بياناتك.",
        time: "تقديري: 1–15 يوم",
      },
    ],
    documents: DOCUMENTS,
    places: [],
  },
  {
    id: "birth-certificate",
    serviceName: "شهادة ميلاد",
    shortName: "شهادة الميلاد",
    description: "استخراج شهادة ميلاد مميكنة لك أو لطفلك.",
    image: birthImg,
    officialLink: EGYPT_DIGITAL_URL,
    lastUpdated: "2026-08-01",
    accessibilityInfo: "الطلب أونلاين متاح ومريح لكبار السن.",
    questions: [
      {
        id: "for",
        text: "الشهادة لمين؟",
        options: [
          { value: "self", label: "ليّا" },
          { value: "child", label: "لطفلي" },
          { value: "relative", label: "لحد من أهلي" },
        ],
      },
      {
        id: "method",
        text: "تحب تستخرجها إزاي؟",
        options: [
          { value: "online", label: "أونلاين بالتوصيل" },
          { value: "office", label: "بنفسي من المكتب" },
        ],
      },
      {
        id: "newborn",
        text: "هل الطفل مولود جديد ولسه ما اتسجلش؟",
        options: yesNo,
        showIf: (a) => a["for"] === "child",
      },
    ],
    requiredDocuments: [
      { docId: "nid" },
      { docId: "form", showIf: (a) => a["method"] === "office" },
      { docId: "photos", showIf: (a) => a["newborn"] === "yes" },
    ],
    steps: [
      { id: "prep", title: "جهّز مستنداتك", detail: "بطاقة الرقم القومي وبيانات الميلاد الكاملة." },
      {
        id: "submit",
        title: "اطلب الشهادة",
        detail: "أونلاين من منصة مصر الرقمية، أو من أقرب مكتب صحة/سجل مدني.",
        cost: "تقديري: 30–75 EGP",
        time: "تقديري: نفس اليوم – 7 أيام",
      },
      { id: "receive", title: "استلم وراجع البيانات", detail: "تأكد من الاسم الرباعي وتاريخ ومحل الميلاد." },
    ],
    documents: DOCUMENTS,
    places: [],
  },
  {
    id: "driving-license",
    serviceName: "رخصة قيادة",
    shortName: "رخصة القيادة",
    description: "رخصة خاصة جديدة أو تجديد، بالخطوات والاختبارات.",
    image: licenseImg,
    officialLink: EGYPT_DIGITAL_URL,
    lastUpdated: "2026-08-01",
    accessibilityInfo: "وحدات المرور الكبيرة فيها شباك خدمة سريعة؛ اسأل عند الاستقبال.",
    questions: [
      {
        id: "type",
        text: "إيه نوع الطلب؟",
        options: [
          { value: "new", label: "رخصة جديدة" },
          { value: "renew", label: "تجديد" },
          { value: "lost", label: "بدل فاقد" },
        ],
      },
      {
        id: "age",
        text: "هل عندك 18 سنة أو أكتر؟",
        options: yesNo,
      },
      {
        id: "school",
        text: "خدت تدريب في مدرسة قيادة؟",
        options: yesNo,
        showIf: (a) => a["type"] === "new",
      },
    ],
    requiredDocuments: [
      { docId: "nid" },
      { docId: "photos" },
      { docId: "medical" },
      { docId: "form" },
      { docId: "drivingTest", showIf: (a) => a["type"] === "new" },
      { docId: "policeReport", showIf: (a) => a["type"] === "lost" },
    ],
    steps: [
      { id: "prep", title: "جهّز مستنداتك", detail: "الكشف الطبي والصور والبطاقة." },
      {
        id: "test",
        title: "امتحان الإشارات والقيادة",
        detail: "الاختبار في وحدة المرور، وبيتكرر لو مش عدّيت.",
        cost: "تقديري: 100–300 EGP",
        showIf: (a) => a["type"] === "new",
      },
      {
        id: "submit",
        title: "قدّم وادفع الرسوم",
        detail: "قدّم الملف في وحدة المرور وخد الإيصال.",
        cost: "تقديري: 200–600 EGP حسب مدة الرخصة",
      },
      { id: "receive", title: "استلم الرخصة", detail: "راجع تاريخ الانتهاء ونوع الرخصة." },
    ],
    documents: DOCUMENTS,
    places: [],
  },
  {
    id: "university",
    serviceName: "إجراءات الجامعة",
    shortName: "الجامعة",
    description: "التسجيل، الملف، والمستندات المطلوبة.",
    image: universityImg,
    officialLink: EGYPT_DIGITAL_URL,
    lastUpdated: "2026-08-01",
    comingSoon: true,
    accessibilityInfo: "",
    questions: [],
    requiredDocuments: [],
    steps: [],
    documents: DOCUMENTS,
    places: [],
  },
  {
    id: "employment",
    serviceName: "أوراق التوظيف",
    shortName: "التوظيف",
    description: "الفيش، التأمينات، وشهادة الخبرة.",
    image: jobImg,
    officialLink: EGYPT_DIGITAL_URL,
    lastUpdated: "2026-08-01",
    comingSoon: true,
    accessibilityInfo: "",
    questions: [],
    requiredDocuments: [],
    steps: [],
    documents: DOCUMENTS,
    places: [],
  },
  {
    id: "bank",
    serviceName: "خدمات بنكية",
    shortName: "البنك",
    description: "فتح حساب، تحديث بيانات، أو بطاقة جديدة.",
    image: bankImg,
    officialLink: EGYPT_DIGITAL_URL,
    lastUpdated: "2026-08-01",
    comingSoon: true,
    accessibilityInfo: "",
    questions: [],
    requiredDocuments: [],
    steps: [],
    documents: DOCUMENTS,
    places: [],
  },
];

export function getService(id: string) {
  return SERVICES.find((s) => s.id === id);
}

/** Questions that apply given current answers. */
export function visibleQuestions(service: Service, answers: Record<string, string>) {
  return service.questions.filter((q) => !q.showIf || q.showIf(answers));
}

export function requiredDocsFor(service: Service, answers: Record<string, string>): DocumentDetail[] {
  return service.requiredDocuments
    .filter((r) => !r.showIf || r.showIf(answers))
    .map((r) => service.documents[r.docId])
    .filter((d): d is DocumentDetail => Boolean(d));
}

export function stepsFor(service: Service, answers: Record<string, string>) {
  return service.steps.filter((s) => !s.showIf || s.showIf(answers));
}
